# https://cloud.redhat.com/experts/o11y/ocp-grafana/
# https://github.com/grafana/grafana-operator
# https://docs.openshift.com/container-platform/4.13/rest_api/operatorhub_apis/operatorgroup-operators-coreos-com-v1.html
# https://operatorhub.io/operator/grafana-operator
# https://grafana.github.io/grafana-operator/docs/
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  targetNamespaces:
  - grafana-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  channel: v5
  name: grafana-operator
  installPlanApproval: Automatic
  source: community-operators
  sourceNamespace: openshift-marketplace
