# https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/security-context-constraints.yaml
# https://docs.openshift.com/container-platform/4.13/authentication/understanding-and-managing-pod-security-admission.html
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  # annotations:
  #   kubernetes.io/description: node-exporter scc is used for the Prometheus node exporter
  # labels:
  #   app.kubernetes.io/managed-by: cluster-monitoring-operator
  #   app.kubernetes.io/part-of: openshift-monitoring
  name: alloy
  namespace: grafana-cloud
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
# seLinuxContext:
#   type: RunAsAny
# seccompProfiles:
# - runtime/default
users:
- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy
- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy-events
#- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy-logs
#- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-opencost
# Allow hostPath for docker / process metrics
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- secret
# Use the `spc_t` selinux type to access the
# docker/cri socket + proc and cgroup stats
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "spc_t"
    level: "s0"
# system-probe requires some specific seccomp and capabilities
seccompProfiles:
- '*'
allowedCapabilities:
- SYS_ADMIN
- SYS_RESOURCE
- SYS_PTRACE
- NET_ADMIN
- NET_BROADCAST
- IPC_LOCK
- NET_RAW
- CHOWN
- AUDIT_CONTROL
- AUDIT_READ
#
# The rest is copied from restricted SCC
#
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowedFlexVolumes: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
# If your environment restricts user access to the Docker socket or journald (for logging)
# create or use an existing group that has access and add the GID to
# the lines below (also remove the previous line, `type: RunAsAny`)
#   type: MustRunAs
#   ranges:
#   - min: <min-group-ID>
#   - max: <max-group-ID>
requiredDropCapabilities: []