# https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/security-context-constraints.yaml
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  # annotations:
  #   kubernetes.io/description: node-exporter scc is used for the Prometheus node exporter
  # labels:
  #   app.kubernetes.io/managed-by: cluster-monitoring-operator
  #   app.kubernetes.io/part-of: openshift-monitoring
  name: alloy
  namespace: grafana-cloud
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- runtime/default
users:
- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy
- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy-events

#- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-opencost
#- system:serviceaccount:grafana-cloud:grafana-k8s-monitoring-alloy-logs

# oc adm policy add-scc-to-user grafana-agent -z grafana-k8s-monitoring-alloy
# oc adm policy add-scc-to-user grafana-agent -z grafana-k8s-monitoring-alloy-events 
# oc adm policy add-scc-to-user grafana-agent -z grafana-k8s-monitoring-alloy-logs
# oc adm policy add-scc-to-user grafana-agent -z grafana-k8s-monitoring-opencost