#https://access.redhat.com/solutions/7002730
apiVersion: v1
kind: Namespace
metadata:
  name: kubeprometheus
  labels:
    pod-security.kubernetes.io/enforce: privileged
    security.openshift.io/scc.podSecurityLabelSync: 'true'
